name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo_mysql, mbstring

      - name: Create .env file
        run: |
          echo "APP_ENV=test" > .env
          echo "DEFAULT_URI=http://localhost" >> .env
          echo "CORS_ALLOW_ORIGIN=^https?://localhost(:[0-9]+)?$" >> .env
          echo "JWT_PASSPHRASE=test" >> .env
        working-directory: meteolive-backend

      - name: Install dependencies
        run: composer install --no-interaction
        working-directory: meteolive-backend

      - name: Run tests
        run: php bin/phpunit
        working-directory: meteolive-backend